# Generated by Django 6.0 on 2025-12-17 12:03

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "title_zh",
                    models.CharField(
                        default="第44屆測量及空間資訊研討會",
                        max_length=255,
                        verbose_name="中文標題",
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        default="SG44 Conference on Surveying and Geomatics",
                        max_length=255,
                        verbose_name="英文副標題",
                    ),
                ),
                (
                    "theme_zh",
                    models.CharField(
                        default="智測國土，韌期未來",
                        max_length=255,
                        verbose_name="中文主題",
                    ),
                ),
                (
                    "theme_en",
                    models.CharField(
                        default="Smart Surveying of National Land, Resilient Future",
                        max_length=255,
                        verbose_name="英文主題",
                    ),
                ),
                (
                    "conference_date",
                    models.CharField(
                        default="2024年 8月 29日 (四) - 30日 (五)",
                        max_length=100,
                        verbose_name="會議日期",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="國立政治大學 法學院",
                        max_length=255,
                        verbose_name="會議地點",
                    ),
                ),
                (
                    "organizer",
                    models.CharField(
                        default="國立政治大學 地政學系",
                        max_length=255,
                        verbose_name="主辦單位",
                    ),
                ),
                (
                    "co_organizer",
                    models.CharField(
                        default="國立政治大學 地政學系",
                        max_length=255,
                        verbose_name="承辦單位",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="sg44@example.com",
                        max_length=254,
                        verbose_name="聯絡信箱",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        default="02-29393091", max_length=50, verbose_name="聯絡電話"
                    ),
                ),
                (
                    "hero_description",
                    wagtail.fields.RichTextField(blank=True, verbose_name="首頁描述"),
                ),
            ],
            options={
                "verbose_name": "研討會首頁",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("重要公告", "重要公告"),
                            ("活動消息", "活動消息"),
                            ("系統更新", "系統更新"),
                        ],
                        max_length=50,
                        verbose_name="分類",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="標題")),
                ("link", models.URLField(blank=True, verbose_name="連結")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_items",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "最新消息",
                "verbose_name_plural": "最新消息",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("title", models.CharField(max_length=100, verbose_name="事件標題")),
                ("is_past", models.BooleanField(default=False, verbose_name="已過期")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "時程事件",
                "verbose_name_plural": "時程事件",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="主題標題")),
                ("description", models.TextField(verbose_name="主題描述")),
                (
                    "icon_name",
                    models.CharField(
                        choices=[
                            ("Map", "地圖"),
                            ("Zap", "閃電"),
                            ("Shield", "盾牌"),
                            ("Globe", "地球"),
                            ("Cpu", "CPU"),
                            ("Database", "資料庫"),
                        ],
                        default="Map",
                        max_length=50,
                        verbose_name="圖示",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "徵稿主題",
                "verbose_name_plural": "徵稿主題",
                "ordering": ["order"],
            },
        ),
    ]
